#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/tee-supplicant

start_service() {
	procd_open_instance

	# Run in foreground, procd manages the backgrounding
	procd_set_param command "$PROG"

	# Restart automatically on crash/exit
	procd_set_param respawn 3600 5 0

	# Send logs to logread
	procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

stop_service() {
	:
}
