#!/bin/sh /etc/rc.common

# Copyright (c) 2022, Qualcomm Innovation Center, Inc. All rights reserved.

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

START=99
USE_PROCD=1

DEVICE_CONTROLLER="Device.LocalAgent.Controller.1"
DEVICE_MTP="Device.LocalAgent.MTP.1.STOMP"
DEVICE_STOMP="Device.STOMP.Connection.1"
DEVICE_LOCALAGENT="Device.LocalAgent"

dbset_function() {
	#If dbfile location is different than the default, use the command obuspa -c dbset -f "filelocation" $1 $2
	obuspa -c dbset $1 $2
}

localagent_config() {
	local localagent=$1
	local endpointid
	config_get endpointid "$localagent" "endpointid" "$localagent"
	dbset_function $DEVICE_LOCALAGENT.EndpointID $endpointid
}

mtp_config() {
	local mtp=$1
	local destination
	config_get destination "$mtp" "destination" "$mtp"
	dbset_function $DEVICE_MTP.Destination $destination
}

controller_config() {
	local controller=$1
	local endpointid
	local alias
	config_get endpointid "$controller" "endpointid" "$controller"
	config_get alias "$controller" "alias" "$controller"
	dbset_function $DEVICE_CONTROLLER.EndpointID $endpointid
	dbset_function $DEVICE_CONTROLLER.Alias $alias
}

connection_config() {
	local connection=$1
	local host
	local username
	local password
	local encryption
	config_get host "$connection" "host" "$connection"
	config_get username "$connection" "username" "$connection"
	config_get password "$connection" "password" "$connection"
	config_get encryption "$connection" "encryption" "$connection"
	dbset_function $DEVICE_STOMP.Host $host
	dbset_function $DEVICE_STOMP.Username $username
	dbset_function $DEVICE_STOMP.Password $password
	dbset_function $DEVICE_STOMP.EnableEncryption $encryption
}

start_service() {
	mkdir -p /var/obuspa
	config_load obuspa
	config_foreach localagent_config localagent
	config_foreach mtp_config mtp
	config_foreach controller_config controller
	config_foreach connection_config connection
}
